version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
        
  web:
    image: para_api
    ports:
      - "80:80"
    depends_on:
      - postgres
        
networks:
  practice: